export * from './damage';
export * from './desire-to-hide';
export * from './fire-torpedo-at-coordinates';
export * from './free-movement';
export * from './mine-placement';
export * from './move-to-coordinates-utility';
export * from './threat-of-being-shot-at-coordinates';
export * from './threat-of-taking-mine-damage';
export * from './trigger-mine-at-coordinates';
